version: '3'

services:
  database:
    image: postgis/postgis:15-master
    ports:
      - '5432:5432'
    environment:
      PGDATA: /var/lib/postgresql/data
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - pgadmin:/var/lib/pgadmin
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)'

  traefik:
    image: traefik:v2.9
    ports:
      - '80:80'
      - '8080:8080'
    command:
      - '--api.insecure=true'
      - '--providers.docker'
      - '--providers.docker.exposedByDefault=false'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  backend:
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /home/app
    env_file:
      - .env
    expose:
      - 8000
    build: .
    volumes:
      - .:/home/app
    profiles:
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=Host(`backend.coffilation.localhost`)'


volumes:
  pgadmin:
  pg:
